
ALTER TABLE Movies
DROP CONSTRAINT fk_actor_id,
DROP CONSTRAINT fk_director_id,
DROP CONSTRAINT fk_writer_id;

DELETE FROM Director;
DELETE FROM Actor;
DELETE FROM Writer;

TRUNCATE TABLE Director RESTART IDENTITY;
TRUNCATE TABLE Actor RESTART IDENTITY;
TRUNCATE TABLE Writer RESTART IDENTITY;
