INSERT INTO Person (name, dateOfBirth, country, email) VALUES
('Arthur C Clarke',NULL ,NULL, 'arthur@clarke.com'),
('George Lucas' ,NULL,'USA','george@email.com'),
('Harper Lee', NULL,NULL,'harper@lee.com'),
('James Cameron',NULL ,'Canada','james@cameron.com'),
('Boris Pasternak',NULL ,NULL,'boris@boris.com'),
('Frederick Frank',NULL ,NULL,'fred@frank.com'),
('Theodoros Angelopoulos',NULL ,'greece','theo@angelopoulos.com'),
('Erik Hazelhoff Roelfzema',NULL ,NULL,'erik@roelfzema.com'),
('Krzysztof Kieslowski',NULL ,'Poland','email@email.com'),
('Edmond Rostand',NULL ,NULL,'edmond@rostand.com'),
('Stanely Kubrick',NULL, 'USA',NULL),
('Robert Mulligan',NULL, 'USA',NULL),
('David Lean',NULL ,'UK',NULL),
('Anthony Mann',NULL, 'USA',NULL),
('Paul Verhoeven',NULL ,'Netherlands',NULL),
('Jean-Paul Rappeneau',NULL, 'France',NULL),
('Keir Duella', '30/05/1936',NULL,NULL),
('Mark Hamill', '25/09/1951',NULL,NULL),
('Gregory Peck', '05/04/1916',NULL,NULL),
('Leonardo DiCaprio', '11/11/1974',NULL,NULL),
('Julie Christie', '14/04/1940',NULL,NULL),
('Charlton Heston', '04/10/1923',NULL,NULL),
('Manos Katrakis', '14/08/1908',NULL,NULL),
('Rutger Hauer', '23/01/1944',NULL,NULL),
('Juliette Binoche','09/03/1964',NULL,NULL),
('Gerard Depardieu','27/12/1948',NULL,NULL);

